# Import Libraries

In [1]:
import pandas as pd
import numpy as np
from collections import Counter
pd.options.display.max_columns=64

# Collect players data from latest update

In [21]:
fpl_all_data_21_24 = pd.read_csv('/Users/ziadNader/Desktop/Personal Projects/Fantasy Premier League/data/processed/all_players_years.csv', 
                                 index_col=0)

In [22]:
fpl_all_data_21_24.sort_values(by='date', inplace=True)

In [24]:
fpl_all_data_21_24['date'].max()

'2024-09-05'

In [26]:
fpl_all_data_21_24.shape

(51187, 54)

In [25]:
fpl_all_data_21_24.isna().sum()

assists                             0
bonus                               0
bps                                 0
chance_of_playing_next_round    20098
chance_of_playing_this_round    20990
clean_sheets                        0
code                                0
cost_change_event                   0
cost_change_event_fall              0
cost_change_start                   0
cost_change_start_fall              0
creativity                          0
dreamteam_count                     0
element_type                        0
ep_next                             3
ep_this                          1764
event_points                        0
first_name                          0
form                                0
goals_conceded                      0
goals_scored                        0
ict_index                           0
i_d                                 0
in_dreamteam                        0
influence                           0
minutes                             0
news                            35774
news_added                      20099
now_cost                            0
own_goals                           0
penalties_missed                    0
penalties_saved                     0
photo                               0
points_per_game                     0
red_cards                           0
saves                               0
second_name                         0
selected_by_percent                 0
special                             0
squad_number                    51187
status                              0
team                                0
team_code                           0
threat                              0
total_points                        0
transfers_in                        0
transfers_in_event                  0
transfers_out                       0
transfers_out_event                 0
value_form                          0
value_season                        0
web_name                            0
yellow_cards                        0
date                                0
dtype: int64

In [27]:
fpl_all_data_21_24

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,i_d,in_dreamteam,influence,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards,date
11164,0,11,625,NaN,NaN,11,80201,0,0,0,0,0.0,0,1,3.6,NaN,0,Bernd,0.0,37,0,70.3,1,False,702.2,3131,NaN,NaN,50,1,0,1,80201.jpg,3.7,1,86,Leno,2.3,False,NaN,a,1,3,2.0,131,0,0,0,0,0.0,26.2,Leno,0,2021-08-13
11527,0,0,0,NaN,NaN,0,81441,0,0,0,0,0.0,0,1,0.0,NaN,0,Mark,0.0,0,0,0.0,514,False,0.0,0,NaN,NaN,40,0,0,0,81441.jpg,0.0,0,0,Gillespie,0.2,False,NaN,a,14,4,0.0,0,0,0,0,0,0.0,0.0,Gillespie,0,2021-08-13
11526,0,0,0,NaN,NaN,0,155503,0,0,0,0,0.0,0,1,0.8,NaN,0,Freddie,0.0,0,0,0.0,513,False,0.0,0,NaN,NaN,45,0,0,0,155503.jpg,0.0,0,0,Woodman,0.2,False,NaN,a,14,4,0.0,0,0,0,0,0,0.0,0.0,Woodman,0,2021-08-13
11525,0,6,376,NaN,NaN,5,57145,0,0,0,0,91.3,0,2,0.7,NaN,0,Federico,0.0,38,0,67.5,465,False,522.0,2080,NaN,NaN,45,1,0,0,57145.jpg,2.2,0,0,Fernández,0.2,False,NaN,a,14,4,64.0,53,0,0,0,0,0.0,11.8,Fernández,4,2021-08-13
11524,0,0,47,NaN,NaN,1,223175,0,0,0,0,35.6,0,3,0.0,NaN,0,Matthew,0.0,8,0,7.0,312,False,32.6,376,NaN,NaN,45,0,0,0,223175.jpg,2.0,0,0,Longstaff,0.1,False,NaN,a,14,4,2.0,10,0,0,0,0,0.0,2.2,M.Longstaff,0,2021-08-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21069,0,0,0,NaN,NaN,0,156074,0,0,-1,1,0.0,0,2,0.5,0.0,0,Rob,0.0,0,0,0.0,202,False,0.0,0,NaN,NaN,44,0,0,0,156074.jpg,0.0,0,0,Holding,0.1,False,NaN,a,7,31,0.0,0,769,284,3207,541,0.0,0.0,Holding,0,2024-09-05
21070,0,0,7,100.0,100.0,0,108413,0,0,-1,1,14.8,0,3,1.2,0.7,0,Will,0.7,3,0,3.5,203,False,14.4,132,NaN,2024-08-23T14:00:06.339937Z,49,0,0,0,108413.jpg,1.0,0,0,Hughes,0.0,False,NaN,a,7,31,6.0,2,1155,513,2099,283,0.1,0.4,Hughes,1,2024-09-05
21071,0,0,21,NaN,NaN,0,209400,0,0,-1,1,62.5,0,3,1.8,1.3,2,Daichi,1.3,4,0,11.1,205,False,22.0,183,NaN,NaN,54,0,0,0,209400.jpg,1.3,0,0,Kamada,0.3,False,NaN,a,7,31,26.0,4,5365,1601,28565,3850,0.2,0.7,Kamada,1,2024-09-05
21073,0,0,12,NaN,NaN,0,231747,-1,1,-1,1,29.8,0,4,2.2,1.7,2,Jean-Philippe,1.7,4,0,4.7,207,False,4.8,203,NaN,NaN,74,0,0,0,231747.jpg,1.7,0,0,Mateta,4.3,False,NaN,a,7,31,14.0,5,143852,15963,313832,65353,0.2,0.7,Mateta,0,2024-09-05
21029,0,0,0,NaN,NaN,0,520295,0,0,-1,1,0.0,0,4,0.0,0.0,0,David Datro,0.0,0,0,0.0,164,False,0.0,0,NaN,NaN,54,0,0,0,520295.jpg,0.0,0,0,Fofana,0.1,False,NaN,a,6,8,0.0,0,4327,1711,7318,1664,0.0,0.0,D.D.Fofana,0,2024-09-05

In [ ]:
* selected period with 23/24 : 13/08/24
* Trend analysis

In [29]:
fpl_all_data_21_24[fpl_all_data_21_24['second_name']=='Haaland']

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,i_d,in_dreamteam,influence,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards,date
15546,0,3,48,NaN,NaN,1,223094,1,-1,1,-1,4.8,1,4,5.5,5.0,13,Erling,13.0,0,2,14.0,318,True,62.6,77,NaN,NaN,116,0,0,0,223094.jpg,13.0,0,0,Haaland,53.6,False,NaN,a,13,43,73.0,13,767457,767457,22648,22648,1.1,1.1,Haaland,0,2022-08-09
2503,1,3,64,NaN,NaN,2,223094,1,-1,2,-2,18.1,1,4,10.0,10.5,5,Erling,9.0,0,2,19.5,318,True,80.8,150,NaN,NaN,117,0,0,0,223094.jpg,9.0,0,0,Haaland,59.9,False,NaN,a,13,43,96.0,18,1338379,194566,97390,67514,0.8,1.5,Haaland,0,2022-08-16
36716,1,6,165,NaN,NaN,2,223094,1,-1,3,-3,31.3,2,4,11.7,11.2,17,Erling,10.2,5,6,51.4,318,True,211.0,323,NaN,NaN,118,0,0,0,223094.jpg,10.2,0,0,Haaland,66.0,False,NaN,a,13,43,271.0,41,2140808,396226,315197,11494,0.9,3.5,Haaland,0,2022-08-29
40896,1,12,278,NaN,NaN,3,223094,1,-1,5,-5,46.9,3,4,11.3,11.8,9,Erling,10.8,6,10,83.8,318,True,349.8,481,NaN,NaN,120,0,0,0,223094.jpg,11.2,0,0,Haaland,78.6,False,NaN,a,13,43,441.0,67,3435320,213071,386460,12285,0.9,5.6,Haaland,0,2022-09-07
45686,1,12,278,NaN,NaN,3,223094,0,0,5,-5,46.9,3,4,13.2,0.0,0,Erling,12.2,6,10,83.8,318,True,349.8,481,NaN,NaN,120,0,0,0,223094.jpg,11.2,0,0,Haaland,80.0,False,NaN,a,13,43,441.0,67,3575209,83946,394071,4812,1.0,5.6,Haaland,0,2022-09-16
6535,1,12,307,NaN,NaN,4,223094,1,-1,6,-6,50.3,3,4,11.7,11.7,6,Erling,10.7,6,11,90.1,318,True,387.4,571,NaN,NaN,121,0,0,0,223094.jpg,10.4,0,0,Haaland,81.1,False,NaN,a,13,43,463.0,73,3724423,90291,414817,17731,0.9,6.0,Haaland,0,2022-09-30
23286,3,15,409,NaN,NaN,4,223094,1,-1,7,-7,95.8,4,4,15.5,15.5,23,Erling,14.5,9,14,120.6,318,True,522.6,661,NaN,NaN,122,0,0,0,223094.jpg,12.0,0,0,Haaland,83.7,False,NaN,a,13,43,587.0,96,4006744,245859,434098,4449,1.2,7.9,Haaland,0,2022-10-08
24538,3,15,432,NaN,NaN,5,223094,0,0,7,-7,116.8,4,4,11.7,12.7,6,Erling,11.7,9,15,133.4,318,True,556.2,751,NaN,NaN,122,0,0,0,223094.jpg,11.3,0,0,Haaland,84.3,False,NaN,a,13,43,660.0,102,4103997,65191,458862,23935,1.0,8.4,Haaland,0,2022-10-14
29440,3,18,485,75.0,NaN,5,223094,0,0,7,-7,142.4,5,4,9.0,12.0,13,Erling,11.0,11,17,162.4,318,True,640.8,920,Knock - 75% chance of playing,2022-10-25T22:30:07.174496Z,122,0,0,0,223094.jpg,10.6,0,0,Haaland,84.1,False,NaN,d,13,43,840.0,117,4568450,79731,947670,24374,0.9,9.6,Haaland,0,2022-10-26
5900,3,18,485,75.0,75.0,5,223094,-1,1,6,-6,142.4,5,4,4.7,4.7,0,Erling,5.2,11,17,162.4,318,True,640.8,920,Knock - 75% chance of playing,2022-10-25T22:30:07.174496Z,121,0,0,0,223094.jpg,10.6,0,0,Haaland,80.2,False,NaN,d,13,43,840.0,117,4677678,86049,1443006,166487,0.4,9.7,Haaland,0,2022-11-04
3142,3,19,517,100.0,100.0,5,223094,0,0,7,-7,176.5,5,4,5.8,5.8,1,Erling,4.8,13,18,178.2,318,True,675.6,1036,NaN,2022-10-25T22:30:07.174496Z,122,0,0,0,223094.jpg,9.5,0,0,Haaland,82.7,False,NaN,a,13,43,929.0,123,5117238,32221,1627124,20370,0.4,10.1,Haaland,2,2022-11-15
14937,3,22,568,100.0,100.0,5,223094,0,0,7,-7,187.7,6,4,14.0,14.0,13,Erling,13.0,14,20,197.8,318,True,755.2,1126,NaN,2022-10-25T22:30:07.174496Z,122,0,0,0,223094.jpg,9.7,0,0,Haaland,84.5,False,NaN,a,13,43,1034.0,136,5353466,46950,1658747,4582,1.1,11.1,Haaland,2,2022-12-30
46351,3,23,588,100.0,100.0,5,223094,0,0,7,-7,189.6,6,4,10.0,10.5,0,Erling,9.5,15,21,204.0,318,True,782.6,1216,NaN,2022-10-25T22:30:07.174496Z,122,0,0,0,223094.jpg,9.5,0,0,Haaland,84.7,False,NaN,a,13,43,1067.0,142,5399424,0,1672542,0,0.8,11.6,Haaland,3,2023-01-02
14236,3,26,704,100.0,100.0,7,223094,0,0,7,-7,215.4,7,4,15.1,7.3,2,Erling,6.8,20,25,237.8,318,True,930.4,1635,NaN,2022-10-25T22:30:07.174496Z,122,0,0,0,223094.jpg,8.6,0,0,Haaland,85.5,False,NaN,a,13,43,1232.0,171,5549255,17747,1738977,12577,0.6,14.0,Haaland,3,2023-02-10
4589,4,26,733,100.0,100.0,7,223094,0,0,7,-7,228.5,8,4,5.0,4.5,2,Erling,3.5,22,26,250.3,318,True,978.4,1860,NaN,2022-10-25T22:30:07.174496Z,122,0,0,0,223094.jpg,8.0,0,0,Haaland,84.9,False,NaN,a,13,43,1300.0,183,5591258,15939,1807100,45992,0.3,15.0,Haaland,3,2023-02-24
7968,5,27,773,100.0,100.0,8,223094,0,0,7,-7,231.7,8,4,5.3,6.3,10,Erling,4.8,22,27,258.9,318,True,1016.0,1931,NaN,2022-10-25T22:30:07.174496Z,122,0,0,0,223094.jpg,8.0,0,0,Haaland,85.2,False,NaN,a,13,43,1345.0,193,5609125,15141,1824806,6946,0.4,15.8,Haaland,3,2023-03-02
36063,6,27,780,100.0,100.0,9,223094,0,0,7,-7,246.0,8,4,5.7,5.2,4,Erling,4.7,22,27,264.1,318,True,1028.8,2021,NaN,2022-10-25T22:30:07.174496Z,122,0,0,0,223094.jpg,7.9,0,0,Haaland,84.8,False,NaN,a,13,43,1370.0,197,5637413,6020,1884650,37858,0.4,16.1,Haaland,4,2023-03-07
26641,6,27,803,100.0,100.0,10,223094,-1,1,6,-6,250.8,8,4,0.0,6.6,6,Erling,5.6,22,28,271.1,318,True,1054.0,2111,NaN,2022-10-25T22:30:07.174496Z,121,0,0,0,223094.jpg,7.8,0,0,Haaland,76.1,False,NaN,a,13,43,1410.0,203,5661185,12528,2672865,664789,0.5,16.8,Haaland,4,2023-03-17
1097,6,27,803,100.0,100.0,10,223094,-1,1,5,-5,250.8,8,4,7.2,0.0,0,Erling,6.7,22,28,271.1,318,True,1054.0,2111,NaN,2022-10-25T22:30:07.174496Z,120,0,0,0,223094.jpg,7.8,0,0,Haaland,75.7,False,NaN,a,13,43,1410.0,203,5735350,72481,3010562,20649,0.6,16.9,Haaland,4,2023-03-21
16236,6,27,803,100.0,75.0,10,223094,0,0,5,-5,250.8,8,4,4.5,2.6,0,Erling,3.0,22,28,271.1,318,True,1054.0,2111,NaN,2023-03-21T11:00:07.837535Z,120,0,0,0,223094.jpg,7.8,0,0,Haaland,72.9,False,NaN,a,13,43,1410.0,203,5989727,195888,3574859,134636,0.2,16.9,Haaland,4,2023-04-07
35314,6,30,852,100.0,100.0,11,223094,1,-1,7,-7,251.1,9,4,7.0,7.5,12,Erling,6.0,22,30,283.4,318,True,1115.2,2179,NaN,2023-03-21T11:00:07.837535Z,122,0,0,0,223094.jpg,8.0,0,0,Haaland,78.3,False,NaN,a,13,43,1471.0,215,6614512,236875,3587847,4007,0.5,17.6,Haaland,5,2023-04-14
1854,6,33,905,100.0,100.0,11,223094,0,0,7,-7,261.4,9,4,0.0,9.0,12,Erling,8.0,22,32,294.8,318,True,1180.6,2224,NaN,2023-03-21T11:00:07.837535Z,122,0,0,0,223094.jpg,8.1,0,0,Haaland,77.8,False,NaN,a,13,43,1509.0,227,6812758,43518,3717796,126719,0.7,18.6,Haaland,5,2023-04-18
19832,6,33,905,100.0,100.0,11,223094,0,0,7,-7,261.4,9,4,8.5,0.0,0,Erling,8.0,22,32,294.8,318,True,1180.6,2224,NaN,2023-03-21T11:00:07.837535Z,122,0,0,0,223094.jpg,8.1,0,0,Haaland,77.8,False,NaN,a,13,43,1509.0,227,7073037,240419,4108553,2853,0.7,18.6,Haaland,5,2023-04-24
22603,8,39,1009,100.0,100.0,12,223094,0,0,9,-9,342.5,11,4,11.8,23.6,16,Erling,10.8,24,35,336.2,318,True,1342.4,2494,NaN,2023-03-21T11:00:07.837535Z,124,0,0,0,223094.jpg,8.3,0,0,Haaland,83.1,False,NaN,a,13,43,1680.0,257,7694922,43414,4117773,3018,0.9,20.7,Haaland,5,2023-05-05
40223,8,39,1002,100.0,100.0,12,223094,0,0,9,-9,347.0,11,4,9.8,9.8,2,Erling,8.8,25,35,341.9,318,True,1345.2,2584,NaN,2023-03-21T11:00:07.837535Z,124,0,0,0,223094.jpg,8.1,0,0,Haaland,83.4,False,NaN,a,13,43,1730.0,259,7750381,7729,4132881,7096,0.7,20.9,Haaland,5,2023-05-09
31451,9,40,1040,NaN,NaN,13,223094,0,0,0,0,371.0,0,4,5.5,NaN,0,Erling,0.0,26,36,358.1,355,False,1390.0,2767,NaN,NaN,140,0,0,0,223094.jpg,7.8,0,0,Haaland,88.0,False,NaN,a,13,43,1825.0,272,0,0,0,0,0.0,19.4,Haaland,5,2023-08-11
30089,0,3,56,NaN,NaN,1,223094,0,0,0,0,23.7,1,4,4.5,5.5,13,Erling,13.0,0,2,13.9,355,True,67.6,79,NaN,NaN,140,0,0,0,223094.jpg,13.0,0,0,Haaland,90.7,False,NaN,a,13,43,48.0,13,127357,127357,12299,12299,0.9,0.9,Haaland,0,2023-08-16
12950,0,3,71,NaN,NaN,2,223094,0,0,0,0,48.4,1,4,7.3,7.8,4,Erling,6.3,1,3,34.6,355,False,105.0,259,NaN,NaN,140,0,1,0,223094.jpg,6.3,0,0,Haaland,91.3,False,NaN,a,13,43,193.0,19,278989,26027,70270,14649,0.4,1.4,Haaland,0,2023-08-29
43591,1,6,161,NaN,NaN,2,223094,1,-1,1,-1,71.8,2,4,9.7,9.7,20,Erling,8.7,2,6,54.4,355,True,224.4,349,NaN,NaN,141,0,1,0,223094.jpg,9.8,0,0,Haaland,92.0,False,NaN,a,13,43,248.0,39,390654,84517,91085,9452,0.6,2.8,Haaland,0,2023-09-15
50910,1,6,176,NaN,NaN,2,223094,0,0,1,-1,86.3,2,4,11.0,11.0,6,Erling,10.0,3,7,71.8,355,True,265.6,439,NaN,NaN,141,0,1,0,223094.jpg,9.0,0,0,Haaland,92.3,False,NaN,a,13,43,366.0,45,430406,21522,99758,3951,0.7,3.2,Haaland,0,2023-09-20
28116,1,6,207,NaN,NaN,3,223094,0,0,1,-1,102.2,2,4,5.2,5.7,2,Erling,4.7,5,8,82.3,355,True,304.0,619,NaN,NaN,141,0,1,0,223094.jpg,7.6,0,0,Haaland,90.7,False,NaN,a,13,43,416.0,53,503567,15904,278440,147043,0.3,3.8,Haaland,0,2023-10-06
19072,1,8,251,NaN,NaN,3,223094,0,0,0,0,124.9,2,4,4.5,5.0,8,Erling,4.0,7,9,92.7,355,True,350.4,799,NaN,NaN,140,0,1,0,223094.jpg,7.0,0,0,Haaland,84.9,False,NaN,a,13,43,450.0,63,574624,18194,899309,266983,0.3,4.5,Haaland,0,2023-10-27
25224,2,11,314,NaN,NaN,4,223094,0,0,0,0,137.7,3,4,9.7,9.2,16,Erling,8.7,7,11,113.5,355,True,439.6,889,NaN,NaN,140,0,1,0,223094.jpg,7.9,0,0,Haaland,84.6,False,NaN,a,13,43,556.0,79,664580,80299,1043409,31618,0.6,5.6,Haaland,0,2023-11-03
3839,2,11,318,75.0,NaN,4,223094,0,0,0,0,139.3,3,4,5.8,7.8,1,Erling,6.8,7,11,115.9,355,True,440.0,934,Ankle injury - 75% chance of playing,2023-11-04T18:30:07.898730Z,140,0,1,0,223094.jpg,7.3,0,0,Haaland,82.7,False,NaN,d,13,43,578.0,80,717169,6374,1256042,203828,0.5,5.7,Haaland,0,2023-11-07
18342,2,11,318,100.0,NaN,4,223094,0,0,0,0,139.3,3,4,9.3,9.3,1,Erling,8.3,7,11,115.9,355,True,440.0,934,NaN,2023-11-04T18:30:07.898730Z,140,0,1,0,223094.jpg,7.3,0,0,Haaland,82.5,False,NaN,a,13,43,578.0,80,728713,17918,1289751,237537,0.6,5.7,Haaland,0,2023-11-09
37400,3,14,375,100.0,100.0,4,223094,0,0,0,0,171.6,4,4,10.7,11.2,16,Erling,10.2,11,13,136.2,355,True,526.4,1024,NaN,2023-11-04T18:30:07.898730Z,140,0,1,0,223094.jpg,8.0,0,0,Haaland,83.0,False,NaN,a,13,43,662.0,96,816646,61708,1343166,7219,0.7,6.9,Haaland,0,2023-11-13
42222,3,15,400,100.0,75.0,4,223094,0,0,0,0,172.6,4,4,9.0,6.4,7,Erling,8.0,12,14,147.0,355,True,562.8,1114,NaN,2023-11-18T18:00:09.529260Z,140,0,1,0,223094.jpg,7.9,0,0,Haaland,83.6,False,NaN,a,13,43,733.0,103,1056026,171182,1513508,15445,0.6,7.4,Haaland,0,2023-12-02
27383,5,15,418,100.0,100.0,4,223094,0,0,0,0,195.9,4,4,11.0,11.0,7,Erling,10.0,15,14,153.4,355,True,576.2,1204,NaN,2023-11-18T18:00:09.529260Z,140,0,1,0,223094.jpg,7.9,0,0,Haaland,83.9,False,NaN,a,13,43,760.0,110,1115226,33573,1526168,10295,0.7,7.9,Haaland,1,2023-12-04
9470,5,15,417,100.0,100.0,4,223094,0,0,0,0,197.5,4,4,9.5,9.0,2,Erling,8.0,16,14,159.8,355,True,588.6,1294,NaN,2023-11-18T18:00:09.529260Z,140,0,1,0,223094.jpg,7.5,0,0,Haaland,84.2,False,NaN,a,13,43,810.0,112,1168458,36432,1547202,11178,0.6,8.0,Haaland,1,2023-12-08
8712,5,15,417,50.0,100.0,4,223094,0,0,0,0,197.5,4,4,3.7,7.9,0,Erling,6.4,16,14,159.8,355,True,588.6,1294,Foot injury - 50% chance of playing,2023-12-10T18:00:10.148960Z,140,0,1,0,223094.jpg,7.5,0,0,Haaland,82.8,False,NaN,d,13,43,810.0,112,1234911,9778,1743463,187454,0.5,8.0,Haaland,1,2023-12-11
47808,5,15,417,50.0,0.0,4,223094,0,0,-1,1,197.5,4,4,0.2,0.0,0,Erling,0.0,16,14,159.8,355,True,588.6,1294,Foot injury - 50% chance of playing,2023-12-10T18:00:10.148960Z,139,0,1,0,223094.jpg,7.5,0,0,Haaland,53.9,False,NaN,d,13,43,810.0,112,1740041,349913,5218544,276290,0.0,8.1,Haaland,1,2024-01-11
49448,6,18,494,100.0,100.0,5,223094,1,-1,4,-4,242.1,5,4,14.6,7.3,13,Erling,6.3,18,16,183.8,355,True,683.8,1488,NaN,2023-12-10T18:00:10.148960Z,144,0,1,0,223094.jpg,7.3,0,0,Haaland,72.6,False,NaN,a,13,43,912.0,131,4225750,537993,5766147,9323,0.4,9.1,Haaland,1,2024-02-16
12203,7,20,541,100.0,100.0,7,223094,-1,1,4,-4,271.8,5,4,7.3,7.8,6,Erling,6.8,20,18,217.3,355,True,755.4,1832,NaN,2023-12-10T18:00:10.148960Z,144,0,1,0,223094.jpg,6.9,0,0,Haaland,74.6,False,NaN,a,13,43,1146.0,152,4868300,48327,6102953,257289,0.5,10.6,Haaland,1,2024-03-09
48623,7,20,550,100.0,100.0,8,223094,0,0,3,-3,306.5,5,4,3.8,3.3,2,Erling,3.3,21,18,225.2,355,True,770.8,2012,NaN,2023-12-10T18:00:10.148960Z,143,0,1,0,223094.jpg,6.5,0,0,Haaland,72.0,False,NaN,a,13,43,1179.0,156,5137294,59158,6657745,48675,0.2,10.9,Haaland,1,2024-04-01
34610,8,29,792,NaN,NaN,11,223094,0,0,0,0,367.2,0,4,5.0,NaN,0,Erling,0.0,25,27,303.3,351,False,1094.6,2553,NaN,NaN,150,0,1,0,223094.jpg,7.0,0,0,Haaland,46.9,False,NaN,a,13,43,1581.0,217,0,0,0,0,0.0,14.5,Haaland,1,2024-08-14
21254,0,8,204,NaN,NaN,1,223094,1,-1,2,-2,15.0,2,4,14.7,14.7,17,Erling,13.7,2,7,44.3,351,True,240.4,269,NaN,NaN,152,0,0,0,223094.jpg,13.7,0,0,Haaland,65.9,False,NaN,a,13,43,187.0,41,1416028,497990,141405,12971,0.9,2.7,Haaland,1,2024-09-05

# Predict next game outcome in terms of bonus points/points per game