In [ ]:
* Exctract all the players
* Add some features ( like next opponent FDR)  and next 5 games average or number of home/away games
* Extract my team 
* suggest a transfer based on characteristics

In [1]:
import pandas as pd

In [3]:
fixtures_list = pd.read_json('/Users/ziadNader/Desktop/Personal Projects/Fantasy Premier League/data/raw/fixtures/fixtures.json')

In [6]:
fixtures_list

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2367869,NaN,False,False,332,NaT,0,True,NaN,7,NaN,5,NaN,[],3,3,93652
1,2367792,NaN,False,False,255,NaT,0,True,NaN,18,NaN,7,NaN,[],3,3,93575
2,2367874,NaN,False,False,337,NaT,0,True,NaN,15,NaN,14,NaN,[],3,4,93657
3,2367876,NaN,False,False,339,NaT,0,True,NaN,13,NaN,18,NaN,[],5,4,93659
4,2367538,1.0,True,True,1,2023-08-11 19:00:00+00:00,90,False,1.0,13,3.0,6,0.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",5,2,93321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2367913,38.0,False,False,376,2024-05-19 15:00:00+00:00,0,False,0.0,2,NaN,8,NaN,[],3,2,93696
376,2367914,38.0,False,False,377,2024-05-19 15:00:00+00:00,0,False,0.0,20,NaN,11,NaN,[],2,5,93697
377,2367915,38.0,False,False,378,2024-05-19 15:00:00+00:00,0,False,0.0,10,NaN,12,NaN,[],2,2,93698
378,2367916,38.0,False,False,379,2024-05-19 15:00:00+00:00,0,False,0.0,19,NaN,13,NaN,[],2,5,93699
379,2367917,38.0,False,False,380,2024-05-19 15:00:00+00:00,0,False,0.0,18,NaN,17,NaN,[],3,2,93700

In [31]:
fixtures_list[fixtures_list['finished']]['stats'].iloc[0]

[{'identifier': 'goals_scored',
  'a': [{'value': 2, 'element': 355}, {'value': 1, 'element': 365}],
  'h': []},
 {'identifier': 'assists',
  'a': [{'value': 1, 'element': 343}, {'value': 1, 'element': 365}],
  'h': []},
 {'identifier': 'own_goals', 'a': [], 'h': []},
 {'identifier': 'penalties_saved', 'a': [], 'h': []},
 {'identifier': 'penalties_missed', 'a': [], 'h': []},
 {'identifier': 'yellow_cards', 'a': [], 'h': []},
 {'identifier': 'red_cards', 'a': [], 'h': [{'value': 1, 'element': 184}]},
 {'identifier': 'saves',
  'a': [{'value': 1, 'element': 352}],
  'h': [{'value': 5, 'element': 596}]},
 {'identifier': 'bonus',
  'a': [{'value': 3, 'element': 355},
   {'value': 2, 'element': 365},
   {'value': 1, 'element': 342}],
  'h': []},
 {'identifier': 'bps',
  'a': [{'value': 56, 'element': 355},
   {'value': 42, 'element': 365},
   {'value': 32, 'element': 342},
   {'value': 27, 'element': 352},
   {'value': 26, 'element': 369},
   {'value': 25, 'element': 343},
   {'value': 25, 'element': 358},
   {'value': 23, 'element': 341},
   {'value': 18, 'element': 356},
   {'value': 11, 'element': 344},
   {'value': 7, 'element': 616},
   {'value': 6, 'element': 353},
   {'value': 4, 'element': 349},
   {'value': 4, 'element': 357},
   {'value': 3, 'element': 360},
   {'value': 1, 'element': 362}],
  'h': [{'value': 22, 'element': 596},
   {'value': 18, 'element': 160},
   {'value': 12, 'element': 157},
   {'value': 12, 'element': 165},
   {'value': 12, 'element': 173},
   {'value': 10, 'element': 176},
   {'value': 8, 'element': 594},
   {'value': 6, 'element': 182},
   {'value': 5, 'element': 168},
   {'value': 5, 'element': 475},
   {'value': 4, 'element': 605},
   {'value': 3, 'element': 161},
   {'value': 3, 'element': 600},
   {'value': -1, 'element': 159},
   {'value': -6, 'element': 184}]}]

In [21]:
from datetime import date

today = date.today()
print("Today's date:", today)

Today's date: 2024-03-28

In [13]:
now = datetime.now()

In [19]:
fixtures_list['kickoff_time'] = pd.to_datetime(fixtures_list['kickoff_time']).dt.date

In [22]:
fixtures_list[fixtures_list['kickoff_time']> today]

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
287,2367834,30.0,False,False,297,2024-03-30,0,False,0.0,19,NaN,15,NaN,[],2,4,93617
288,2367828,30.0,False,False,292,2024-03-30,0,False,0.0,9,NaN,3,NaN,[],2,2,93612
289,2367831,30.0,False,False,294,2024-03-30,0,False,0.0,6,NaN,7,NaN,[],2,3,93614
290,2367835,30.0,False,False,298,2024-03-30,0,False,0.0,8,NaN,16,NaN,[],2,2,93618
291,2367836,30.0,False,False,299,2024-03-30,0,False,0.0,10,NaN,17,NaN,[],2,2,93619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2367913,38.0,False,False,376,2024-05-19,0,False,0.0,2,NaN,8,NaN,[],3,2,93696
376,2367914,38.0,False,False,377,2024-05-19,0,False,0.0,20,NaN,11,NaN,[],2,5,93697
377,2367915,38.0,False,False,378,2024-05-19,0,False,0.0,10,NaN,12,NaN,[],2,2,93698
378,2367916,38.0,False,False,379,2024-05-19,0,False,0.0,19,NaN,13,NaN,[],2,5,93699
379,2367917,38.0,False,False,380,2024-05-19,0,False,0.0,18,NaN,17,NaN,[],3,2,93700

In [24]:
fpl_data = pd.read_csv('/Users/ziadNader/Desktop/Personal Projects/Fantasy Premier League/data/Files/Players/2024-03-09_fpl_players.csv')

In [33]:
fpl_data.news

0                                  Transferred to Monaco
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
                             ...
827                                                  NaN
828                                                  NaN
829    On loan to Villarreal until the end of the season
830                                                  NaN
831                                                  NaN
Name: news, Length: 832, dtype: object

In [40]:
fpl_data.team_code

0       3
1       3
2       3
3       3
4       3
       ..
827    39
828    39
829    39
830    39
831    39
Name: team_code, Length: 832, dtype: int64