In [42]:
import os
import pandas as pd
pd.options.display.max_columns=64

In [12]:
directory  = '../data/Files/Players/'

In [13]:
os.listdir(directory)

['2021-11-19_fpl_players.csv',
 '2021-08-13_teams.csv',
 '2023-03-21_fpl_players.csv',
 '2022-09-30_teams.csv',
 '2023-04-18_fpl_players.csv',
 '2022-08-16_fpl_players.csv',
 '2022-11-15_fpl_players.csv',
 '2022-05-25_teams.csv',
 '2023-02-24_fpl_players.csv',
 '2022-03-02_teams.csv',
 '2023-04-24_teams.csv',
 '2021-10-26_fpl_players.csv',
 '2022-11-04_fpl_players.csv',
 '2021-11-19_teams.csv',
 '.DS_Store',
 '2022-09-30_fpl_players.csv',
 '2023-08-16_teams.csv',
 '2022-04-29_fpl_players.csv',
 '2023-02-24_teams.csv',
 '2021-12-03_teams.csv',
 '2023-03-02_fpl_players.csv',
 '2021-12-22_teams.csv',
 '2023-05-05_teams.csv',
 '2022-11-04_teams.csv',
 '2022-08-29_teams.csv',
 '2023-03-17_teams.csv',
 '2022-03-11_fpl_players.csv',
 '2022-01-21_fpl_players.csv',
 '2021-08-13_fpl_players.csv',
 '2023-08-11_teams.csv',
 '2022-10-08_teams.csv',
 '2021-12-28_teams.csv',
 '2022-08-16_teams.csv',
 '2022-04-22_teams.csv',
 '2023-08-29_fpl_players.csv',
 '2021-10-20_teams.csv',
 '2021-08-21_fpl_players.csv',
 '2023-02-10_fpl_players.csv',
 '2022-12-30_fpl_players.csv',
 '2021-10-01_teams.csv',
 '2022-02-11_teams.csv',
 '2022-08-09_fpl_players.csv',
 '2023-04-07_fpl_players.csv',
 '2022-03-03_teams.csv',
 '2023-08-29_teams.csv',
 '2022-05-05_teams.csv',
 '2021-12-22_fpl_players.csv',
 '2021-08-21_teams.csv',
 '2022-03-24_fpl_players.csv',
 '2022-09-16_teams.csv',
 '2022-04-29_teams.csv',
 '2023-04-24_fpl_players.csv',
 '2023-05-09_teams.csv',
 '2022-03-11_teams.csv',
 '2022-02-17_teams.csv',
 '2022-08-09_teams.csv',
 '2022-04-11_teams.csv',
 '2022-05-25_fpl_players.csv',
 '2021-10-20_fpl_players.csv',
 '2023-02-10_teams.csv',
 '2022-03-24_teams.csv',
 '2022-01-21_teams.csv',
 '2023-05-05_fpl_players.csv',
 '2023-03-02_teams.csv',
 '2021-10-26_teams.csv',
 '2022-10-08_fpl_players.csv',
 '2021-10-01_fpl_players.csv',
 '2022-09-07_teams.csv',
 '2022-10-14_fpl_players.csv',
 '2021-08-24_teams.csv',
 '2021-12-28_fpl_players.csv',
 '2023-03-17_fpl_players.csv',
 '2022-02-06_teams.csv',
 '2021-12-13_teams.csv',
 '2023-10-06_fpl_players.csv',
 '2023-04-07_teams.csv',
 '2021-12-03_fpl_players.csv',
 '2023-03-07_teams.csv',
 '2023-01-02_teams.csv',
 '2022-10-26_fpl_players.csv',
 '2023-08-16_fpl_players.csv',
 '2022-03-02_fpl_players.csv',
 '2023-08-11_fpl_players.csv',
 '2022-04-22_fpl_players.csv',
 '2023-04-18_teams.csv',
 '2022-02-11_fpl_players.csv',
 '2021-08-24_fpl_players.csv',
 '2021-08-16_fpl_players.csv',
 '2022-10-14_teams.csv',
 '2022-12-30_teams.csv',
 '2021-11-02_teams.csv',
 '2023-04-14_fpl_players.csv',
 '2023-03-07_fpl_players.csv',
 '2022-08-29_fpl_players.csv',
 '2022-03-03_fpl_players.csv',
 '2021-11-02_fpl_players.csv',
 '2023-09-20_teams.csv',
 '2022-04-07_fpl_players.csv',
 '2023-05-09_fpl_players.csv',
 '2022-09-07_fpl_players.csv',
 '2023-09-15_teams.csv',
 '2021-11-29_teams.csv',
 '2022-10-26_teams.csv',
 '2021-11-29_fpl_players.csv',
 '2021-12-13_fpl_players.csv',
 '2023-09-15_fpl_players.csv',
 '2022-02-06_fpl_players.csv',
 '2022-11-15_teams.csv',
 '2022-04-11_fpl_players.csv',
 '2022-09-16_fpl_players.csv',
 '2021-08-16_teams.csv',
 '2023-01-02_fpl_players.csv',
 '2022-05-05_fpl_players.csv',
 '2023-04-14_teams.csv',
 '2022-02-17_fpl_players.csv',
 '2023-03-21_teams.csv',
 '2023-10-06_teams.csv',
 '2023-09-20_fpl_players.csv',
 '2022-04-07_teams.csv']

In [28]:
#players_data_fpl_23_24 = pd.DataFrame()
appended_data = []
for f in os.listdir(directory):
    if 'csv' in f:
        data = pd.read_csv(os.path.join(directory, f))
        data['date'] = f[:10]
        appended_data.append(data)
        
players_data_fpl_23_24 = pd.concat(appended_data)

In [34]:
players_data_fpl_23_24['date'].value_counts(dropna=False).sort_index()

2021-08-13    550
2021-08-16    574
2021-08-21    579
2021-08-24    586
2021-10-01    631
2021-10-20    637
2021-10-26    638
2021-11-02    643
2021-11-19    644
2021-11-29    653
2021-12-03    656
2021-12-13    667
2021-12-22    681
2021-12-28    685
2022-01-21    711
2022-02-06    722
2022-02-11    725
2022-02-17    727
2022-03-02    734
2022-03-03    734
2022-03-11    734
2022-03-24    734
2022-04-07    740
2022-04-11    742
2022-04-22    746
2022-04-29    748
2022-05-05    750
2022-05-25    757
2022-08-09    595
2022-08-16    605
2022-08-29    621
2022-09-07    644
2022-09-16    647
2022-09-30    651
2022-10-08    658
2022-10-14    661
2022-10-26    668
2022-11-04    676
2022-11-15    687
2022-12-30    695
2023-01-02    703
2023-02-10    760
2023-02-24    766
2023-03-02    766
2023-03-07    767
2023-03-17    770
2023-03-21    771
2023-04-07    774
2023-04-14    774
2023-04-18    779
2023-04-24    780
2023-05-05    782
2023-05-09    783
2023-08-11    661
2023-08-16    683
2023-08-29    705
2023-09-15    734
2023-09-20    737
2023-10-06    742
Name: date, dtype: int64

In [37]:
players_data_fpl_23_24 = players_data_fpl_23_24[players_data_fpl_23_24['date'] > '2023-08-01']

In [51]:
players_data_fpl_23_24[players_data_fpl_23_24['second_name'] == 'Haaland']

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,i_d,in_dreamteam,influence,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards,date,id,name,strength,short_name,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away
424,0.0,3.0,71.0,NaN,NaN,2.0,223094,0.0,0.0,0.0,0.0,48.4,1.0,4.0,7.3,7.8,4.0,Erling,6.3,1.0,3.0,34.6,355.0,False,105.0,259.0,NaN,NaN,140.0,0.0,1.0,0.0,223094.jpg,6.3,0.0,0.0,Haaland,91.3,False,NaN,a,13.0,43.0,193.0,19.0,278989.0,26027.0,70270.0,14649.0,0.4,1.4,Haaland,0.0,2023-08-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
444,1.0,6.0,207.0,NaN,NaN,3.0,223094,0.0,0.0,1.0,-1.0,102.2,2.0,4.0,5.2,5.7,2.0,Erling,4.7,5.0,8.0,82.3,355.0,True,304.0,619.0,NaN,NaN,141.0,0.0,1.0,0.0,223094.jpg,7.6,0.0,0.0,Haaland,90.7,False,NaN,a,13.0,43.0,416.0,53.0,503567.0,15904.0,278440.0,147043.0,0.3,3.8,Haaland,0.0,2023-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,0.0,3.0,56.0,NaN,NaN,1.0,223094,0.0,0.0,0.0,0.0,23.7,1.0,4.0,4.5,5.5,13.0,Erling,13.0,0.0,2.0,13.9,355.0,True,67.6,79.0,NaN,NaN,140.0,0.0,0.0,0.0,223094.jpg,13.0,0.0,0.0,Haaland,90.7,False,NaN,a,13.0,43.0,48.0,13.0,127357.0,127357.0,12299.0,12299.0,0.9,0.9,Haaland,0.0,2023-08-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,9.0,40.0,1040.0,NaN,NaN,13.0,223094,0.0,0.0,0.0,0.0,371.0,0.0,4.0,5.5,NaN,0.0,Erling,0.0,26.0,36.0,358.1,355.0,False,1390.0,2767.0,NaN,NaN,140.0,0.0,0.0,0.0,223094.jpg,7.8,0.0,0.0,Haaland,88.0,False,NaN,a,13.0,43.0,1825.0,272.0,0.0,0.0,0.0,0.0,0.0,19.4,Haaland,5.0,2023-08-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
437,1.0,6.0,161.0,NaN,NaN,2.0,223094,1.0,-1.0,1.0,-1.0,71.8,2.0,4.0,9.7,9.7,20.0,Erling,8.7,2.0,6.0,54.4,355.0,True,224.4,349.0,NaN,NaN,141.0,0.0,1.0,0.0,223094.jpg,9.8,0.0,0.0,Haaland,92.0,False,NaN,a,13.0,43.0,248.0,39.0,390654.0,84517.0,91085.0,9452.0,0.6,2.8,Haaland,0.0,2023-09-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,1.0,6.0,176.0,NaN,NaN,2.0,223094,0.0,0.0,1.0,-1.0,86.3,2.0,4.0,11.0,11.0,6.0,Erling,10.0,3.0,7.0,71.8,355.0,True,265.6,439.0,NaN,NaN,141.0,0.0,1.0,0.0,223094.jpg,9.0,0.0,0.0,Haaland,92.3,False,NaN,a,13.0,43.0,366.0,45.0,430406.0,21522.0,99758.0,3951.0,0.7,3.2,Haaland,0.0,2023-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
players_data_fpl_23_24

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,creativity,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,goals_conceded,goals_scored,ict_index,i_d,in_dreamteam,influence,minutes,news,news_added,now_cost,own_goals,penalties_missed,penalties_saved,photo,points_per_game,red_cards,saves,second_name,selected_by_percent,special,squad_number,status,team,team_code,threat,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards,date,id,name,strength,short_name,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away
0,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-16,1.0,Arsenal,4.0,ARS,1230.0,1285.0,1250.0,1250.0,1210.0,1320.0
1,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-16,2.0,Aston Villa,3.0,AVL,1115.0,1175.0,1130.0,1190.0,1100.0,1160.0
2,NaN,NaN,NaN,NaN,NaN,NaN,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-16,3.0,Bournemouth,3.0,BOU,1060.0,1095.0,1050.0,1100.0,1060.0,1090.0
3,NaN,NaN,NaN,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-16,4.0,Brentford,3.0,BRE,1125.0,1205.0,1120.0,1220.0,1130.0,1190.0
4,NaN,NaN,NaN,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-08-16,5.0,Brighton,3.0,BHA,1165.0,1210.0,1120.0,1200.0,1210.0,1240.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,0.0,0.0,4.0,NaN,NaN,0.0,87835,0.0,0.0,-1.0,1.0,11.2,0.0,2.0,0.5,-0.5,0.0,Matt,0.0,2.0,0.0,2.5,598.0,False,4.6,30.0,NaN,NaN,44.0,0.0,0.0,0.0,87835.jpg,0.0,0.0,0.0,Doherty,0.2,False,NaN,a,20.0,39.0,9.0,0.0,2771.0,254.0,12712.0,650.0,0.0,0.0,Doherty,0.0,2023-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
713,0.0,0.0,0.0,NaN,NaN,0.0,231480,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.5,-0.5,0.0,Santiago,0.0,0.0,0.0,0.0,697.0,False,0.0,0.0,NaN,NaN,45.0,0.0,0.0,0.0,231480.jpg,0.0,0.0,0.0,Bueno,0.0,False,NaN,a,20.0,39.0,0.0,0.0,291.0,84.0,78.0,44.0,0.0,0.0,S.Bueno,0.0,2023-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
714,0.0,0.0,0.0,NaN,NaN,0.0,593001,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.5,-0.5,0.0,Enso,0.0,0.0,0.0,0.0,698.0,False,0.0,0.0,NaN,NaN,50.0,0.0,0.0,0.0,593001.jpg,0.0,0.0,0.0,González,0.0,False,NaN,a,20.0,39.0,0.0,0.0,164.0,51.0,66.0,42.0,0.0,0.0,González,0.0,2023-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
715,0.0,0.0,0.0,NaN,NaN,0.0,531363,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.5,-0.5,0.0,Nathan,0.0,0.0,0.0,0.0,704.0,False,0.0,0.0,NaN,NaN,45.0,0.0,0.0,0.0,531363.jpg,0.0,0.0,0.0,Fraser,0.0,False,NaN,a,20.0,39.0,0.0,0.0,2428.0,708.0,439.0,222.0,0.0,0.0,Fraser,0.0,2023-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
716,0.0,0.0,6.0,NaN,NaN,0.0,231057,0.0,0.0,0.0,0.0,11.3,0.0,3.0,2.2,1.2,2.0,Jean-Ricner,2.0,1.0,0.0,2.6,715.0,False,6.0,76.0,NaN,NaN,50.0,0.0,0.0,0.0,231057.jpg,2.0,0.0,0.0,Bellegarde,0.0,False,NaN,a,20.0,39.0,9.0,2.0,983.0,810.0,85.0,71.0,0.4,0.4,Bellegarde,0.0,2023-09-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN